language: c

sudo: required
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_r stringr
  - ./travis-tool.sh install_r MASS
  - ./travis-tool.sh install_r fields
  - ./travis-tool.sh install_r parallel
  - ./travis-tool.sh install_r spam
  - ./travis-tool.sh install_r grid
  - ./travis-tool.sh install_r maps

script:
  - Rscript -e "library(testthat);test_dir('.')"

notifications:
  email: false
